export default {
  MARK_NOTIFICATIONS_AS_READ: 'MARK_NOTIFICATIONS_AS_READ',
  MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
  TOGGLE_NOTIFICATION_LOADING: 'TOGGLE_NOTIFICATION_LOADING',
}